version: '3.8'

# On dÃ©finit un rÃ©seau commun pour Ãªtre sÃ»r qu'ils se voient
networks:
  app-network:
    driver: bridge

services:
  # ----------------------------
  # 1. Base de donnÃ©es MongoDB
  # ----------------------------
  mongo-db:
    image: mongo:4.4
    container_name: all-scans-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  # ðŸ‘ˆ On le met dans le rÃ©seau

  # ----------------------------
  # 2. Backend (FastAPI)
  # ----------------------------
  backend:
    build: ./backend
    container_name: all-scans-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      # L'URI doit correspondre exactement au nom du service "mongo-db"
      - MONGO_URI=mongodb://mongo-db:27017
      - MONGO_DB_NAME=All_scans
    depends_on:
      - mongo-db
    volumes:
      - ./backend:/app
    networks:
      - app-network # ðŸ‘ˆ Lui aussi

  # ----------------------------
  # 3. Frontend (React)
  # ----------------------------
  frontend:
    build: ./frontend
    container_name: all-scans-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      # Important pour que le front sache oÃ¹ taper (pour les appels API)
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    networks:
      - app-network

volumes:
  mongo-data: